// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIR8LWg33C8FjhcZnic_xz8VJW8sGGUvs',
    appId: '1:584153539050:web:c735d9cc06d44dc97d1293',
    messagingSenderId: '584153539050',
    projectId: 'flutterfire-918f7',
    authDomain: 'flutterfire-918f7.firebaseapp.com',
    storageBucket: 'flutterfire-918f7.appspot.com',
    measurementId: 'G-CE457M5GWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt0gED_YoNTjh3xcqpo3CJSnFsiEn61gs',
    appId: '1:584153539050:android:50f53c52338256817d1293',
    messagingSenderId: '584153539050',
    projectId: 'flutterfire-918f7',
    storageBucket: 'flutterfire-918f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHEjszMHHVRQYaMKdd6TjJWBZGVvc6n_s',
    appId: '1:584153539050:ios:78d9db297bed56457d1293',
    messagingSenderId: '584153539050',
    projectId: 'flutterfire-918f7',
    storageBucket: 'flutterfire-918f7.appspot.com',
    iosClientId: '584153539050-ie7g7n6md9c7bnktll9l0chpcin5krqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHEjszMHHVRQYaMKdd6TjJWBZGVvc6n_s',
    appId: '1:584153539050:ios:96b6988fc5d62d5e7d1293',
    messagingSenderId: '584153539050',
    projectId: 'flutterfire-918f7',
    storageBucket: 'flutterfire-918f7.appspot.com',
    iosClientId: '584153539050-slk6sqe6tuj5dh4bhm25d55qheiqd9rl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfire.RunnerTests',
  );
}
